// Generated by gencpp from file service_method/addResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_METHOD_MESSAGE_ADDRESPONSE_H
#define SERVICE_METHOD_MESSAGE_ADDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_method
{
template <class ContainerAllocator>
struct addResponse_
{
  typedef addResponse_<ContainerAllocator> Type;

  addResponse_()
    : sum(0.0)  {
    }
  addResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef float _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::service_method::addResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_method::addResponse_<ContainerAllocator> const> ConstPtr;

}; // struct addResponse_

typedef ::service_method::addResponse_<std::allocator<void> > addResponse;

typedef boost::shared_ptr< ::service_method::addResponse > addResponsePtr;
typedef boost::shared_ptr< ::service_method::addResponse const> addResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_method::addResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_method::addResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_method::addResponse_<ContainerAllocator1> & lhs, const ::service_method::addResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_method::addResponse_<ContainerAllocator1> & lhs, const ::service_method::addResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_method

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_method::addResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_method::addResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_method::addResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_method::addResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_method::addResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_method::addResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_method::addResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f720a7bfc448e377e8e2dd877c1aef43";
  }

  static const char* value(const ::service_method::addResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf720a7bfc448e377ULL;
  static const uint64_t static_value2 = 0xe8e2dd877c1aef43ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_method::addResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_method/addResponse";
  }

  static const char* value(const ::service_method::addResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_method::addResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 sum\n"
"\n"
;
  }

  static const char* value(const ::service_method::addResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_method::addResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_method::addResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_method::addResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<float>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_METHOD_MESSAGE_ADDRESPONSE_H
